---
title: "MFSS Homework 9"
author: "Ryan Tracy"
date: "5/12/2019"
output: pdf_document
---

#9.1
Show that
$$\begin{bmatrix} 2 & 10 & 2 & -3 \\ 8 & -4 & 5 & -8 \\ 0 & 5 & -1 & 6 \\ -8 & 4 & -4 & 3 \end{bmatrix} \frac{1}{11} \begin{bmatrix} -44.5 & 138 & 99 & 125.5 \\ -4 & 15 & 11 & 14 \\ 100 & -309 & -220 & -284 \\ 20 & -64 & -44 & -59 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

And
$$\frac{1}{11} \begin{bmatrix} -44.5 & 138 & 99 & 125.5 \\ -4 & 15 & 11 & 14 \\ 100 & -309 & -220 & -284 \\ 20 & -64 & -44 & -59 \end{bmatrix}\begin{bmatrix} 2 & 10 & 2 & -3 \\ 8 & -4 & 5 & -8 \\ 0 & 5 & -1 & 6 \\ -8 & 4 & -4 & 3 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

Start by bringing $\frac{1}{11}$ to the front:
$$\frac{1}{11} \begin{bmatrix} 2 & 10 & 2 & -3 \\ 8 & -4 & 5 & -8 \\ 0 & 5 & -1 & 6 \\ -8 & 4 & -4 & 3 \end{bmatrix} \begin{bmatrix} -44.5 & 138 & 99 & 125.5 \\ -4 & 15 & 11 & 14 \\ 100 & -309 & -220 & -284 \\ 20 & -64 & -44 & -59 \end{bmatrix}$$
$$(1,1) \ element = \frac{1}{11} \bigg((2 \times -44.5) + (10 \times -4) + (2 \times 100) + (-3 \times 20) \bigg) = 1$$
$$(1,2) \ element = \frac{1}{11} \bigg((2 \times 138) + (10 \times 15) + (2 \times -309) + (-3 \times -64) \bigg) = 0$$
$$(1,3) \ element = \frac{1}{11} \bigg((2 \times 99) + (10 \times 11) + (2 \times -220) + (-3 \times -44) \bigg) = 0$$
$$(1,4) \ element = \frac{1}{11} \bigg((2 \times 125.5) + (10 \times 14) + (2 \times -284) + (-3 \times -59) \bigg) = 0$$
$$(2,1) \ element = \frac{1}{11} \bigg((8 \times -44.5) + (-4 \times -4) + (5 \times 100) + (-8 \times 20) \bigg) = 0$$
$$(2,2) \ element = \frac{1}{11} \bigg((8 \times 138) + (-4 \times 15) + (5 \times -309) + (-8 \times -64) \bigg) = 1$$
$$(2,3) \ element = \frac{1}{11} \bigg((8 \times 99) + (-4 \times 11) + (5 \times -220) + (-8 \times -44) \bigg) = 0$$
$$(2,4) \ element = \frac{1}{11} \bigg((8 \times 125.5) + (-4 \times 14) + (5 \times -284) + (-8 \times -59) \bigg) = 0$$
$$(3,1) \ element = \frac{1}{11} \bigg((0 \times -44.5) + (5 \times -4) + (-1 \times 100) + (6 \times 20) \bigg) = 0$$
$$(3,2) \ element = \frac{1}{11} \bigg((0 \times 138) + (5 \times 15) + (-1 \times -309) + (6 \times -64) \bigg) = 0$$
$$(3,3) \ element = \frac{1}{11} \bigg((0 \times 99) + (5 \times 11) + (-1 \times -220) + (6 \times -44) \bigg) = 1$$
$$(3,4) \ element = \frac{1}{11} \bigg((0 \times 125.5) + (5 \times 14) + (-1 \times -284) + (6 \times -59) \bigg) = 0$$
$$(4,1) \ element = \frac{1}{11} \bigg((-8 \times -44.5) + (4 \times -4) + (-4 \times 100) + (3 \times 20) \bigg) = 0$$
$$(4,2) \ element = \frac{1}{11} \bigg((-8 \times 138) + (4 \times 15) + (-4 \times -309) + (3 \times -64) \bigg) = 0$$
$$(4,3) \ element = \frac{1}{11} \bigg((-8 \times 99) + (4 \times 11) + (-4 \times -220) + (3 \times -44) \bigg) = 0$$
$$(4,4) \ element = \frac{1}{11} \bigg((-8 \times 125.5) + (4 \times 14) + (-4 \times -284) + (3 \times -59) \bigg) = 1$$
Because the product is equal to
$$\begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$
the first matrix is the left-inverse of the second.

To show that they're full inverses of each other, compute the second product:
$$\frac{1}{11} \begin{bmatrix} -44.5 & 138 & 99 & 125.5 \\ -4 & 15 & 11 & 14 \\ 100 & -309 & -220 & -284 \\ 20 & -64 & -44 & -59 \end{bmatrix}\begin{bmatrix} 2 & 10 & 2 & -3 \\ 8 & -4 & 5 & -8 \\ 0 & 5 & -1 & 6 \\ -8 & 4 & -4 & 3 \end{bmatrix}$$
$$(1,1) \ element = \frac{1}{11} \bigg((-44.5 \times 2) + (138 \times 8) + (99 \times 0) + (125.5 \times -8) \bigg) = 1$$
$$(1,2) \ element = \frac{1}{11} \bigg((-44.5 \times 10) + (138 \times -4) + (99 \times 5) + (125.5 \times 4) \bigg) = 0$$
$$(1,3) \ element = \frac{1}{11} \bigg((-44.5 \times 2) + (138 \times 5) + (99 \times -1) + (125.5 \times -4) \bigg) = 0$$
$$(1,4) \ element = \frac{1}{11} \bigg((-44.5\times -3) + (138 \times -8) + (99 \times 6) + (125.5 \times 3) \bigg) = 0$$
$$(2,1) \ element = \frac{1}{11} \bigg((-4 \times 2) + (15 \times 8) + (11 \times 0) + (14 \times -8) \bigg) = 0$$
$$(2,2) \ element = \frac{1}{11} \bigg((-4 \times 10) + (15 \times -4) + (11 \times 5) + (14 \times 4) \bigg) = 1$$
$$(2,3) \ element = \frac{1}{11} \bigg((-4 \times 2) + (15 \times 5) + (11 \times -1) + (14 \times -4) \bigg) = 0$$
$$(2,4) \ element = \frac{1}{11} \bigg((-4 \times -3) + (15 \times -8) + (11 \times 6) + (14 \times 3) \bigg) = 0$$
$$(3,1) \ element = \frac{1}{11} \bigg((100 \times 2) + (-309 \times 8) + (-220 \times 0) + (-284 \times -8) \bigg) = 0$$
$$(3,2) \ element = \frac{1}{11} \bigg((100 \times 10) + (-309 \times -4) + (-220 \times 5) + (-284 \times 4) \bigg) = 0$$
$$(3,3) \ element = \frac{1}{11} \bigg((100 \times 2) + (-309 \times 5) + (-220 \times -1) + (-284 \times -4) \bigg) = 1$$
$$(3,4) \ element = \frac{1}{11} \bigg((100 \times -3) + (-309 \times -8) + (-220 \times 6) + (-284 \times 3) \bigg) = 0$$
$$(4,1) \ element = \frac{1}{11} \bigg((20 \times 2) + (-64 \times 8) + (-44 \times 0) + (-59 \times -8) \bigg) = 0$$
$$(4,2) \ element = \frac{1}{11} \bigg((20 \times 10) + (-64 \times -4) + (-44 \times 5) + (-59 \times 4) \bigg) = 0$$
$$(4,3) \ element = \frac{1}{11} \bigg((20 \times 2) + (-64 \times 5) + (-44 \times -1) + (-59 \times -4) \bigg) = 0$$
$$(4,4) \ element = \frac{1}{11} \bigg((20 \times -3) + (-64 \times -8) + (-44 \times 6) + (-59 \times 3) \bigg) = 1$$

Because the product is also equal to
$$\begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

These two matrices are full inverses of each other.


#9.3

##a.
$$\begin{bmatrix} 3 & 6 & 6 \\ -3 & 4 & 6 \\ -9 & 0 & 5 \end{bmatrix}$$
Minor elements:
$$M_{11} = \begin{vmatrix} \begin{bmatrix} 4 & 6 \\ 0 & 5 \end{bmatrix} \end{vmatrix} = (4 \times 5) - (6 \times 0) = 20$$
$$M_{12} = \begin{vmatrix} \begin{bmatrix} -3 & 6 \\ -9 & 5 \end{bmatrix} \end{vmatrix} = (-3 \times 5) - (6 \times -9) = 39$$
$$M_{13} = \begin{vmatrix} \begin{bmatrix} -3 & 4 \\ -9 & 0 \end{bmatrix} \end{vmatrix} = (-3 \times 0) - (4 \times -9) = 36$$
$$M_{21} = \begin{vmatrix} \begin{bmatrix} 6 & 6 \\ 0 & 5 \end{bmatrix} \end{vmatrix} = (6 \times 5) - (6 \times 0) = 30$$
$$M_{22} = \begin{vmatrix} \begin{bmatrix} 3 & 6 \\ -9 & 5 \end{bmatrix} \end{vmatrix} = (3 \times 5) - (6 \times -9) = 69$$
$$M_{23} = \begin{vmatrix} \begin{bmatrix} 3 & 6 \\ -9 & 0 \end{bmatrix} \end{vmatrix} = (3 \times 0) - (6 \times -9) = 54$$
$$M_{31} = \begin{vmatrix} \begin{bmatrix} 6 & 6 \\ 4 & 6 \end{bmatrix} \end{vmatrix} = (6 \times 6) - (6 \times 4) = 12$$
$$M_{32} = \begin{vmatrix} \begin{bmatrix} 3 & 6 \\ -3 & 6 \end{bmatrix} \end{vmatrix} = (3 \times 6) - (6 \times -3) = 36$$
$$M_{33} = \begin{vmatrix} \begin{bmatrix} 3 & 6 \\ -3 & 4 \end{bmatrix} \end{vmatrix} = (3 \times 4) - (6 \times -3) = 30$$

The cofactors matrix is then
$$C = \begin{bmatrix} 20 & -39 & 36 \\ -30 & 69 & -54 \\ 12 & -36 & 30 \end{bmatrix}$$

Transposing the cofactors matrix yields the adjoint matrix
$$C' = \begin{bmatrix} 20 & -30 & 12 \\ -39 & 69 & -36 \\ 36 & -54 & 30 \end{bmatrix}$$

The determinant is found by
$$(3 \times 20) + (6 \times -39) + (6 \times 36) = 42$$

Then multiply the determinant's reciprocal by the adjoint matrix
$$\frac{1}{42} \begin{bmatrix} 20 & -30 & 12 \\ -39 & 69 & -36 \\ 36 & -54 & 30 \end{bmatrix} = \begin{bmatrix} .48 & -.71 & .29 \\ -.93 & 1.64 & -.86 \\ .86 & -1.29 & .71 \end{bmatrix}$$


#9.4

##a.
Multiply the elements of 
$$\begin{bmatrix} 6 & -9 & -8 \\ -5 & 4 & 10 \\ -9 & 8 & 6 \end{bmatrix}$$

Down and to the right
$$(6 \times 4 \times 6) = 162$$
$$(-9 \times 10 \times -9) = 144$$
$$(-8 \times -5 \times 8) = 320$$

And down and to the left
$$(6 \times 10 \times 8) = 480$$
$$(-9 \times - 5 \times 6) = 270$$
$$(-8 \times 4 \times -9) = 288$$

Summing the products from the first set and subtracting the summed products from the second set gives the determinant
$$(144+810+320) - (480+270+288) = 236$$


#9.6
Finding the determinant of a $(4 \times 4)$ matrix involves finding the determinant of 4 $(3 \times 3)$ matrices. This would take the student 4 minutes. For a $(5 \times 5)$ matrix, they would be required to find 5 determinants of $(4 \times 4)$ at 4 minutes each, thus taking 20 minutes $(4 \times 5 = 20)$. Following this logic, a $(6 \times 6)$ matrix would mean finding determinants of 6 $(5 \times 5)$ matrices, taking 120 minutes. A $(7 \times 7)$ matrix, with 7 determinants of $(6 \times 6)$ matrices, would take 840 minutes, or 14 hours.

A computer could find the determinant of a $(4 \times 4)$ matrix in 4(.1) = .4 seconds, a $(5 \times 5)$ matrix in 5(.4) = 2 seconds, a $(6 \times 6)$ matrix in 6(2) = 12 seconds, and a $(7 \times 7)$ matrix in 7(12) = 84 seconds.


#9.7

##a.
$$\begin{vmatrix} \begin{bmatrix} 8-\lambda & 7 \\ 7 & 8-\lambda \end{bmatrix} \end{vmatrix} = 0$$
$$(8-\lambda)^2 - 49 = 0$$
$$(64 - 16\lambda + \lambda^2) - 49 = 0$$
$$\lambda^2 - 16\lambda + 15 = 0$$
$$(\lambda-15)(\lambda-1) = 0$$
$$\lambda = 1, \ \lambda = 15$$


#9.8

##a.
$$\begin{bmatrix} 3 & -3 & 0 \\ 1 & 7 & -1 \\ -4 & 4 & 6 \end{bmatrix}$$

Interchange the first and second rows
$$\begin{bmatrix} 1 & 7 & -1 \\  3 & -3 & 0 \\ -4 & 4 & 6 \end{bmatrix}$$

Multiply the first row by -3 and add it to the second row
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & -24 & -3 \\ -4 & 4 & 6 \end{bmatrix}$$

Then multiply the first row by 4 and add it to the third row
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & -24 & -3 \\ 0 & 32 & 10 \end{bmatrix}$$

Divide the second row by -3 and the third row by 2
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & 8 & 1 \\ 0 & 16 & 5 \end{bmatrix}$$

Multiply the second row by -2 and add it to the third row
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & 8 & 1 \\ 0 & 0 & 3 \end{bmatrix}$$

Divide the third row by 3
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & 8 & 1 \\ 0 & 0 & 1 \end{bmatrix}$$

Add the third row to the first and multiply the third row by -1 and add it to the second
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & 8 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

Divide the second row by 8
$$\begin{bmatrix} 1 & 7 & -1 \\  0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

Add -7 times the second row to the first row
$$\begin{bmatrix} 1 & 0 & 0 \\  0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

The rank is 3.

##b.
$$\begin{bmatrix} -2 & 4 & -1 & 3 \\ 1 & 6 & 0 & 2 \\ 3 & 5 & -2 & -1 \\ 4 & 14 & -5 & 1 \end{bmatrix}$$

Swap the first two rows
$$\begin{bmatrix} 1 & 6 & 0 & 2 \\ -2 & 4 & -1 & 3 \\ 3 & 5 & -2 & -1 \\ 4 & 14 & -5 & 1 \end{bmatrix}$$

Add 2 times the first row to the second, 03 times the first row to the third, and -4 times the first row to the fourth
$$\begin{bmatrix} 1 & 6 & 0 & 2 \\ 0 & 16 & -1 & 7 \\ 0 & -13 & -2 & -7 \\ 0 & -10 & -5 & -7 \end{bmatrix}$$

Multiply the first three rows by 10 then swap the second and fourth rows
$$\begin{bmatrix} 10 & 60 & 0 & 20 \\ 0 & -10 & -5 & -7 \\ 0 & 160 & -10 & 70 \\ 0 & -130 & -20 & -70 \end{bmatrix}$$

Add 16 times the second row to the third
$$\begin{bmatrix} 10 & 60 & 0 & 20 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & -90 & -42 \\ 0 & -130 & -20 & -70 \end{bmatrix}$$

Add -13 times the second row to the fourth row
$$\begin{bmatrix} 10 & 60 & 0 & 20 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & -90 & -42 \\ 0 & 0 & 45 & 21 \end{bmatrix}$$

Divide the third row by 2 and add it to the fourth row
$$\begin{bmatrix} 10 & 60 & 0 & 20 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & -45 & -21 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Divide the third row by -3
$$\begin{bmatrix} 10 & 60 & 0 & 20 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & 15 & 7 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Add 6 times the second row to the first
$$\begin{bmatrix} 10 & 0 & -30 & -22 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & 15 & 7 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Add 2 times the third row to the first
$$\begin{bmatrix} 10 & 0 & 0 & -8 \\ 0 & -10 & -5 & -7 \\ 0 & 0 & 15 & 7 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Multiply the second row by 3
$$\begin{bmatrix} 10 & 0 & 0 & -8 \\ 0 & -30 & -15 & -21 \\ 0 & 0 & 15 & 7 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Add the third row to the second
$$\begin{bmatrix} 10 & 0 & 0 & -8 \\ 0 & -30 & 0 & -14 \\ 0 & 0 & 15 & 7 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Divide the first row by 10, the second row by -30, and the third row by 15
$$\begin{bmatrix} 1 & 0 & 0 & -\frac{4}{5} \\ 0 & 1 & 0 & \frac{7}{15} \\ 0 & 0 & 1 & \frac{7}{15} \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

There is an identity matrix in the first three rows and columns, and because there are three rows that do not consist of all 0s, the matrix rank is 3. Because this matrix is not full column rank, it is singular, there is a linear dependency in the rows and columns, the determinant is 0, and it has no inverse.


##c.
$$\begin{bmatrix} 5 & -2 & 3 & 0 \\ -4 & 6 & 8 & 1 \\ 1 & 4 & 11 & 1 \\ 9 & -8 & -5 & -1 \end{bmatrix}$$

Interchange the first and third rows
$$\begin{bmatrix} 1 & 4 & 11 & 1 \\ -4 & 6 & 8 & 1 \\ 5 & -2 & 3 & 0 \\ 9 & -8 & -5 & -1 \end{bmatrix}$$

Multiply the first row by 4 and add it to the second row, multiply it by -5 and add it to the third row, and multiply it by -9 and add it to the third row
$$\begin{bmatrix} 1 & 4 & 11 & 1 \\ 0 & 22 & 49 & 5 \\ 0 & -22 & -52 & -5 \\ 0 & -44 & -104 & -10 \end{bmatrix}$$

Add the second row to the third and add 2 times the second row to the fourth
$$\begin{bmatrix} 1 & 4 & 11 & 1 \\ 0 & 22 & 49 & 5 \\ 0 & 0 & -3 & 0 \\ 0 & 0 & -6 & 0 \end{bmatrix}$$

Add two times the third row to the fourth row
$$\begin{bmatrix} 1 & 4 & 11 & 1 \\ 0 & 22 & 49 & 5 \\ 0 & 0 & -3 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Divide the third row by -3
$$\begin{bmatrix} 1 & 4 & 11 & 1 \\ 0 & 22 & 49 & 5 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Add -49 times the third row to the second row and -11 times the third row to the first row
$$\begin{bmatrix} 1 & 4 & 0 & 1 \\ 0 & 22 & 0 & 5 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Multiply the first row by 11
$$\begin{bmatrix} 11 & 44 & 0 & 11 \\ 0 & 22 & 0 & 5 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Add -2 times the second row to the first
$$\begin{bmatrix} 11 & 0 & 0 & 1 \\ 0 & 22 & 0 & 5 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Divide the first row by 11 and the second row by 22
$$\begin{bmatrix} 1 & 0 & 0 & \frac{1}{11} \\ 0 & 1 & 0 & \frac{5}{22} \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

The matrix rank is 3, and it is singular, there is a linear dependency, its determinant is 0, and it has no inverse.

##d.
$$\begin{bmatrix} 1 & -5 & 8 \\ 2 & -3 & 4 \\ 6 & 0 & 3 \\ 9 & 1 & 3 \\ -4 & 4 & 0 \end{bmatrix}$$
This matrix is not square, so it cannot be full rank. It may be full column rank

Multiply the first row by -2 and add it to the third row, then multiply it by -6 and add it to the third row, then multiply it by -9 and add it to the fourth row, then multiply it by 4 and add it to the fifth row
$$\begin{bmatrix} 1 & -5 & 8 \\ 0 & 7 & -12 \\ 0 & 30 & -45 \\ 0 & -44 & -69 \\ 0 & -16 & 32 \end{bmatrix}$$

Interchange the second and fifth rows
$$\begin{bmatrix} 1 & -5 & 8 \\ 0 & -16 & 32 \\ 0 & 30 & -45 \\ 0 & -44 & -69 \\ 0 & 7 & -12 \end{bmatrix}$$

Divide the second row by -16, the third row by 15, and the fourth by -3
$$\begin{bmatrix} 1 & -5 & 8 \\ 0 & 1 & -2 \\ 0 & 2 & -3 \\ 0 & 18 & -23 \\ 0 & 7 & -12 \end{bmatrix}$$

Multiply the second row by -2 and add it to the third row, then multiply the second row by -18 and add it to the fourth row, then multiply the second row by -7 and add it to the fifth row, then multiply the third row by -1
$$\begin{bmatrix} 1 & -5 & 8 \\ 0 & 1 & -2 \\ 0 & 0 & 1 \\ 0 & 0 & 13 \\ 0 & 0 & 2 \end{bmatrix}$$

Multiply the third row by -8 and add it to the first row, by 2 and add it to the second row, by -13 and add it to the fourth row, and -2 and add it to the fifth row
$$\begin{bmatrix} 1 & -5 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

Add 5 times the second row to the first row
$$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$$

The rank is 3 and the matrix is of full column rank.


#10.3

##a.
This system's matrix is
$$\begin{bmatrix} 1 & -2 & -1 & \Bigg| & 15 \\ -1 & -1 & 1 & \Bigg| & -6 \\ 1 & -6 & -1 & \Bigg| & -43 \end{bmatrix}$$

Add the first row to the second and add -1 times the first row to the third
$$\begin{bmatrix} 1 & -2 & -1 & \Bigg| & 15 \\ 0 & -3 & 0 & \Bigg| & 9 \\ 0 & -4 & 0 & \Bigg| & -58 \end{bmatrix}$$

Divide the second row by -3 and the third row by -4
$$\begin{bmatrix} 1 & -2 & -1 & \Bigg| & 15 \\ 0 & 1 & 0 & \Bigg| & -3 \\ 0 & 1 & 0 & \Bigg| & 14.5 \end{bmatrix}$$

Add -2 times the second row to the first wor and -1 times the second row to the third row
$$\begin{bmatrix} 1 & 0 & -1 & \Bigg| & 21 \\ 0 & 1 & 0 & \Bigg| & -3 \\ 0 & 0 & 0 & \Bigg| & 20.5 \end{bmatrix}$$

The system of equations has been reduced to 
$$x - z = 21$$
$$y = -3$$
$$0 = 20.5$$

The third equation is a false statement, thus the system of equatinos has no solution

##b.
This systems' matrix is
$$\begin{bmatrix} -4 & -1 & -2 & \Bigg| & 15 \\ 1 & -2 & 2 & \Bigg| & 18 \\ 0 & -6 & 4 & \Bigg| & 20 \end{bmatrix}$$

Move the first row to the third position and shift the others up
$$\begin{bmatrix} 1 & -2 & 2 & \Bigg| & 18 \\ 0 & -6 & 4 & \Bigg| & 20 \\ -4 & -1 & -2 & \Bigg| & 15 \end{bmatrix}$$

Add 4 times the first row to the third row
$$\begin{bmatrix} 1 & -2 & 2 & \Bigg| & 18 \\ 0 & -6 & 4 & \Bigg| & 20 \\ 0 & -9 & 6 & \Bigg| & 87 \end{bmatrix}$$

Divide the second row by 2
$$\begin{bmatrix} 1 & -2 & 2 & \Bigg| & 18 \\ 0 & -3 & 2 & \Bigg| & 10 \\ 0 & -9 & 6 & \Bigg| & 87 \end{bmatrix}$$

Multiply the second row by -3 and add it to the third row
$$\begin{bmatrix} 1 & -2 & 2 & \Bigg| & 18 \\ 0 & -3 & 2 & \Bigg| & 10 \\ 0 & 0 & 0 & \Bigg| & 57 \end{bmatrix}$$

This makes the third equation $0 = 57$ which is false, and the system thus has  no solution

##c.
The matrix for this system is
$$\begin{bmatrix} -6 & -2 & 5 & \Bigg| & -29 \\ 2 & -5 & 1 & \Bigg| & -4 \\ 4 & 5 & -5 & \Bigg| & 28 \end{bmatrix}$$

Rearrange the rows by moving the first to the bottom and shifting the others up
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 4 & 5 & -5 & \Bigg| & 28 \\ -6 & -2 & 5 & \Bigg| & -29 \end{bmatrix}$$

Add -2 times the first row to the second and 3 times the first row to the third
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 0 & 15 & -7 & \Bigg| & 36 \\ 0 & -17 & 8 & \Bigg| & -41 \end{bmatrix}$$

Multiply the second row by 17 and the third row by 15
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 0 & 255 & -119 & \Bigg| & 612 \\ 0 & -255 & 120 & \Bigg| & -615 \end{bmatrix}$$

Add the second row to the third
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 0 & 255 & -119 & \Bigg| & 612 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

Then add 119 times the third row to the second
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 0 & 255 & 0 & \Bigg| & 255 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

Divide the second row by 255
$$\begin{bmatrix} 2 & -5 & 1 & \Bigg| & -4 \\ 0 & 1 & 0 & \Bigg| & 1 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

Add -1 times the third row to the first row
$$\begin{bmatrix} 2 & -5 & 0 & \Bigg| & -1 \\ 0 & 1 & 0 & \Bigg| & 1 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

Add 5 times the second row to the first row
$$\begin{bmatrix} 2 & 0 & 0 & \Bigg| & 4 \\ 0 & 1 & 0 & \Bigg| & 1 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

Divide the first row by 2
$$\begin{bmatrix} 1 & 0 & 0 & \Bigg| & 2 \\ 0 & 1 & 0 & \Bigg| & 1 \\ 0 & 0 & 1 & \Bigg| & -3 \end{bmatrix}$$

This implies one unique solution for the system:
$$\begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 2 \\ 1 \\ -3 \end{bmatrix}$$

##d.
This equation system's matrix is
$$\begin{bmatrix} -1 & 3 & -1 & \Bigg| & 9 \\ 1 & -1 & 0 & \Bigg| & -8 \\ -5 & 3 & 1 & \Bigg| & 39 \end{bmatrix}$$

Swap the first and second rows
$$\begin{bmatrix} 1 & -1 & 0 & \Bigg| & -8 \\ -1 & 3 & -1 & \Bigg| & 9 \\ -5 & 3 & 1 & \Bigg| & 39 \end{bmatrix}$$

Add the first row to the second and 5 times the first row to the third
$$\begin{bmatrix} 1 & -1 & 0 & \Bigg| & -8 \\ 0 & 2 & -1 & \Bigg| & 1 \\ 0 & -2 & 1 & \Bigg| & -1 \end{bmatrix}$$

Add the second row to the third
$$\begin{bmatrix} 1 & -1 & 0 & \Bigg| & -8 \\ 0 & 2 & -1 & \Bigg| & 1 \\ 0 & 0 & 0 & \Bigg| & 0 \end{bmatrix}$$

Because $0 = 0$ is true, the system has infinitely many solutions.
